### ISSUE TITLE
Version missmatch missing properties inside SignalRConfiguration 2.1.1 

### ISSUE THREAD

**Issue by Stradivario** [HNeukermans/ng2-signalr#103]
Hello to everyone!

I wanted to ask you what is happening with this library ? 

When i install it and inject SignalRConfiguration interface on defining signalRmodule.forRoot config it says that after 2.0.0 version it will have 3 more properties 

executeEventsInZone
executeErrorsInZone
executeStatusChangeInZone

these 3 properties are missing when i install npm install ng2-signalr

![screenshot from 2018-02-07 11-15-41](https://user-images.githubusercontent.com/19847933/35908049-42990ae0-0bf8-11e8-8bdd-27137ac8421c.png)

I try to look inside the installed library SignalRConfiguration what ive  found is this:

![screenshot from 2018-02-07 11-16-15](https://user-images.githubusercontent.com/19847933/35908087-540b1b9c-0bf8-11e8-9063-bffa7798e09f.png)

Installed version of the library is  2.1.1 

![screenshot from 2018-02-07 11-17-00](https://user-images.githubusercontent.com/19847933/35908131-6e9121c8-0bf8-11e8-8d52-15cbaaf5211e.png)

But when i checked inside your github repository there is https://github.com/HNeukermans/ng2-signalr/blob/master/src/services/signalr.configuration.ts in which everything seems fine...

Please check your Version tagging because now i don't know which version i am facing to.

I think you forgot to update NPM package with the new version... i don't know why ?

Regards,
Kristiyan Tachev

**Comment by thduttonuk** [comment]
Trying to get access so I can do a publish. I have published to my npm as a temp fix. 

> npm i @tom.dutton/ng2-signalr
