### ISSUE TITLE
Question: Regarding Resolve<SignalRConnection>

### ISSUE THREAD

**Issue by michaeled** [HNeukermans/ng2-signalr#105]
Apologies, I'm overlooking the obvious.
Why would we re-establish a WebSocket connection when changing routes? It would seem that establishing the connection once in a global variable and relying on that connection would be more efficient. What am I missing?

**Comment by HNeukermans** [comment]
Indeed. Establishing connection globally can be better idea.
Creating a connection in every route change might seem overkill
