### ISSUE TITLE
Possibility to set LOGGING on or off during runtime

### ISSUE THREAD

**Issue by pcedendahl** [HNeukermans/ng2-signalr#116]
Hi,
I want to be able to turn the logging on or off. Today you need to set the logging status in AppModule. Changing this will force us to re-compile the project. This I think don't make it possible to have a configuration file in the ASSETS folder to configure the LOGGING status. This can then be changed without re-compiling the app. Maby restarting the app but that's ok.

**Comment by thduttonuk** [comment]
This has been done in v9.0.4
