### ISSUE TITLE
Unsubscribe from _listeners

### ISSUE THREAD

**Issue by DonBrowny** [HNeukermans/ng2-signalr#126]
Hi,
All the hub notifications listened via _listenfor_ method are stored on the private variable _listeners (_signalr.connection.ts_ file), **is there any provision to remove** the elements from this array, i.e., unsubscribe to the server notification. Because I need to unsubscribe to a particular event after a certain event is over.

**Comment by kishok** [comment]
@DonBrowny  Use **stopListening()** to off the specific listener to server event.

**Comment by sudhanshu077** [comment]
Hi,
I am trying to use stopListening() function. but it gives me error. stopListening is not a function.

my code
`this.connection.stopListening(new BroadcastEventListener<any>('onDevTaskAdded'));`

can you please explain more how to do it
