### ISSUE TITLE
integrating with Angular 7

### ISSUE THREAD

**Issue by robertmazzo** [HNeukermans/ng2-signalr#134]
Hello,
I'm struggling to get the client to work with Angular 7. I'm following the resolver pattern you specified in your docs, as well as your online demo; however my connection string is always undefined. i.e. pulling from  `route.snapshot.data['connection']` returns nothing.

I am getting a `Cors` error on `http://localhost:54322//signalr/negotiate...`, and even when I set `jsonp = true` on the SignalRConfiguration object in message.module, I get `403 (Forbidden: JSONP is disabled.)` errors in Chrome.

I created this online project for collaboration purposes, if anyone can help: https://stackblitz.com/edit/signalr-hub?file=angular.json 

I am getting, however, `jquery` reference errors when stackblitz runs the project. I've added jquery to the `scripts` array in `angular.json` as per the docs (of course after adding the dependencies to the project).

Thank you.
Bob

**Comment by thduttonuk** [comment]
This should be good with Angular 8
