### ISSUE TITLE
Angular7 + ASP.NET Core: 404 on connect

### ISSUE THREAD

**Issue by Myrmex** [HNeukermans/ng2-signalr#135]
I'm new to SignalR and trying to implement with it a simple scenario with Angular7 client using this library, and ASP.NET Core web API. All what I need is to use SignalR to notify the client about the progress of some lengthy operations in some methods of the API controllers. Yet, I keep getting a 404 at my connection attempts. I post here the details, which might also be useful to other newcomers (also, the documentation should be slightly updated for Angular 7, as shown below, but this is trivial). Probably I'm just doing something wrong, could anyone give a hint?

Looking at the answer posted at <https://github.com/HNeukermans/ng2-signalr/issues/69>, this does not seem to be my case, as the built URL looks good. If I add a trailing `/` to the configured URL, I get a double `//` in the URI.

Also, I setup CORS following the official code sample, so I'd exclude it is a CORS issue.

My start point for the server side was <https://msdn.microsoft.com/en-us/magazine/mt846469.aspx>, plus some docs at <https://docs.microsoft.com/en-us/aspnet/core/signalr/hubs?view=aspnetcore-2.2>. I tried to create a dummy experimental solution with that.

This is my procedure: as for the **server side**:

1.create a new ASP.NET core web API app. No authentication or Docker just to keep it minimal.
2.add the NuGet package `Microsoft.AspNetCore.SignalR`.
3.at `Startup.cs`, `ConfigureServices`, add (before `AddMvc`):

```cs
// CORS
services.AddCors(o => o.AddPolicy("CorsPolicy", builder =>
{
    builder.AllowAnyMethod()
        .AllowAnyHeader()
        .WithOrigins("http://localhost:4200");
}));
// SignalR
services.AddSignalR();
```

In `Configure`, add (after `UseMvc`):

```cs
// CORS
app.UseCors("CorsPolicy");
// SignalR: add to the API at route "/progress"
app.UseSignalR(routes =>
{
    routes.MapHub<ProgressHub>("/progress");
});
```

4.add a `ProgressHub` class, which just derives from `Hub`:

```cs
    public class ProgressHub : Hub
    {
    }
```

5.add a `TaskController` with a method to start some lengthy operation:

```cs
[Route("api/task")]
[ApiController]
public class TaskController : ControllerBase
{
    private readonly IHubContext<ProgressHub> _progressHubContext;

    public TaskController(IHubContext<ProgressHub> progressHubContext)
    {
        _progressHubContext = progressHubContext;
    }

    [HttpGet("lengthy")]
    public IActionResult Lengthy([Bind(Prefix = "id")] string connectionId)
    {
        _progressHubContext
            .Clients
            .Client(connectionId)
            .SendAsync("taskStarted");

        for (int i = 0; i < 100; i++)
        {
            Thread.Sleep(500);
            _progressHubContext
                .Clients
                .Client(connectionId)
                .SendAsync("taskProgressChanged", i);
        }

        _progressHubContext
            .Clients
            .Client(connectionId)
            .SendAsync("taskEnded");

        return Ok();
    }
}
```

If I launch the API and point the browser to `https://localhost:44348/api/task/lengthy?id=1`, I can step into the method code, see it send its messages, and ending as expected.

As for the **client side**:

1.create a new Angular7 CLI app (without routing, just to keep it simple).
2.`npm install ng2-signalr jquery signalr --save`
3.add to `angular.json` (under `projects/architect`):

```json
"scripts": [
  "./node_modules/jquery/dist/jquery.min.js",
  "./node_modules/signalr/jquery.signalR.js"
],
```

4.in `app.module`:

```ts
import { SignalRModule } from 'ng2-signalr';
import { SignalRConfiguration } from 'ng2-signalr';

export function createConfig(): SignalRConfiguration {
  const c = new SignalRConfiguration();
  c.hubName = 'Ng2SignalRHub';
  c.qs = { user: 'dummy' };
  c.url = 'https://localhost:44348';
  c.logging = true;

  c.executeEventsInZone = true; // optional, default is true
  c.executeErrorsInZone = false; // optional, default is false
  c.executeStatusChangeInZone = true; // optional, default is true
  return c;
}
```

and under `imports` I add `SignalRModule.forRoot(createConfig)`.

5.my `app.component`:

```ts
import { Component } from '@angular/core';
import { SignalR, IConnectionOptions } from 'ng2-signalr';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public messages: string[];

  constructor(private _signalR: SignalR) {
  }

  public startJob() {
    this.messages = [];
    const options: IConnectionOptions = { hubName: 'progress' };
    this._signalR.connect(options).then(connection => {
      const taskEvent$ = connection.listenFor('taskProgressChanged');
      taskEvent$.subscribe(m => {
        console.log(m);
        this.messages.push(m.toString());
      })
    });
    // TODO invoke job
  }
}
```

Its minimalist template:

```html
<h2>Test</h2>
<button type="button" (click)="startJob()">start</button>
<div>
  <p *ngFor="let m of messages">{{m}}</p>
</div>
```

If I'm not wrong, this should connect to the progress hub so that once I invoke the API controller's method it will send its progress messages, which will be received by this client code. Yet, I immediately get a 404 as soon as I try to `connect`. Here is the dump:

	Creating connecting with...
	signalr.js:64 configuration:[url: 'https://localhost:44348'] ...
	signalr.js:65 configuration:[hubName: 'progress'] ...
	signalr.js:66 configuration:[qs: '{"user":"dummy"}'] ...
	signalr.js:67 configuration:[transport: '{"_name":"auto"}'] ...

	zone.js:3243 GET https://localhost:44348/signalr/negotiate?clientProtocol=2.0&user=dummy&connectionData=%5B%7B%22name%22%3A%22progress%22%7D%5D&_=1551349335954 404

	scheduleTask @ zone.js:3243
	push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:410
	onScheduleTask @ zone.js:301
	push../node_modules/zone.js/dist/zone.js.ZoneDelegate.scheduleTask @ zone.js:404
	push../node_modules/zone.js/dist/zone.js.Zone.scheduleTask @ zone.js:238
	push../node_modules/zone.js/dist/zone.js.Zone.scheduleMacroTask @ zone.js:261
	scheduleMacroTaskWithCurrentZone @ zone.js:1245
	(anonymous) @ zone.js:3276
	proto.(anonymous function) @ zone.js:1569
	send @ jquery.min.js:2
	ajax @ jquery.min.js:2
	ajax @ jquery.signalR.js:1248
	negotiate @ jquery.signalR.js:715
	(anonymous) @ jquery.signalR.js:833
	start @ jquery.signalR.js:834
	(anonymous) @ signalr.connection.js:49
	ZoneAwarePromise @ zone.js:910
	push../node_modules/ng2-signalr/src/services/connection/signalr.connection.js.SignalRConnection.start @ signalr.connection.js:47
	push../node_modules/ng2-signalr/src/services/signalr.js.SignalR.connect @ signalr.js:48
	push../src/app/app.component.ts.AppComponent.startJob @ app.component.ts:18
	(anonymous) @ app.component.html:1
	handleEvent @ core.js:23106
	callWithDebugContext @ core.js:24176
	debugHandleEvent @ core.js:23903
	dispatchEvent @ core.js:20555
	(anonymous) @ core.js:21002
	(anonymous) @ platform-browser.js:993
	push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:423
	onInvokeTask @ core.js:17289
	push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask @ zone.js:422
	push../node_modules/zone.js/dist/zone.js.Zone.runTask @ zone.js:195
	push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask @ zone.js:498
	invokeTask @ zone.js:1744
	globalZoneAwareCallback @ zone.js:1770
	signalr.connection.js:61 Could not connect

**Comment by mrhussain0334** [comment]
Any solution was found? or do I have to change library?

**Comment by Romanchuk** [comment]
@Myrmex As i know package "signalr" is not compatable with .NET Core Signalr. You should use "@aspnet/signalr" instead. But i doubt that ng2-signalr would work with "@aspnet/signalr", it must to be updated or rewritten in order to support @aspnet/signalr
