### ISSUE TITLE
Azure SignalR Service compatability

### ISSUE THREAD

**Issue by jchawkjr** [HNeukermans/ng2-signalr#140]
Trying to connect to azure signalr service with 8.0.1

You are using a version of the client that isn't compatible with the server. Client version 2.1, server version undefined.

Anybody been down this road?

Tnx - John

**Comment by neil445** [comment]
Do you really need to use this?

I don't use this for Azure SignalR Service.
Microsoft recommends @aspnet/signalr for Azure SignalR Service.

**Comment by thduttonuk** [comment]
You should use the service mentions by @neil445
