### ISSUE TITLE
Angular 9 support

### ISSUE THREAD

**Issue by wizgob** [HNeukermans/ng2-signalr#150]
Is it possible to add Angular 9 support?

The NPM package requires Angular version ^8.0.3
```
  "peerDependencies": {
    "@angular/common": "^8.0.3",
    "@angular/core": "^8.0.3"
  },
```
(in https://github.com/HNeukermans/ng2-signalr/blob/master/projects/ng2-signalr/package.json)

This cause a warning when running npm after upgrading to angular 9:
```
npm WARN ng2-signalr@8.0.2 requires a peer of @angular/common@^8.0.3 but none is installed. You must install peer dependencies yourself.
npm WARN ng2-signalr@8.0.2 requires a peer of @angular/core@^8.0.3 but none is installed. You must install peer dependencies yourself.
```

Testing on our application did not show any problems, changing the peerDependencies as below could be enough:
```
"peerDependencies": {
    "@angular/common": ">=8.0.3",
    "@angular/core": ">=8.0.3"
}
```

**Comment by thduttonuk** [comment]
Angular 9 update has been published. Sorry for the delay
