### ISSUE TITLE
Newbie help please

### ISSUE THREAD

**Issue by shaulbehr** [HNeukermans/ng2-signalr#18]
Hi,
I'm trying to integrate ng2-signalr into my ng2 project.
The sample code given on the home page does not compile. (`this.connection` does not exist).
Do you have some working sample code that demonstrates usage?
Thanks!

**Comment by HNeukermans** [comment]
sure:
https://github.com/HNeukermans/ng2-signalr.demo.webui.systemjs 
https://github.com/HNeukermans/ng2-signalr.demo.webui (webpack)

you can follow the 'live demo' link to see the systemjs repo live

**Comment by HNeukermans** [comment]
I added a 'Create connection' section to the readme.

**Comment by shaulbehr** [comment]
In `documentation.component.tx` you have:
```
this.connection = this.route.snapshot.data['connection'];
```
But I couldn't find where the `connection` property of the `snapshot.data` is being set.  How do you set the connection?

**Comment by shaulbehr** [comment]
I'm guessing I don't actually need to use the `route.snapshot.data`; I could just inject a `SignalR` object into my class where I need to start listening to stuff.
Thing is, in your sample, you've got a static configuration to connect to SignalR.  In 99.9% of real world cases, though (including my app), you'll need to authenticate before being allowed to connect to the SignalR hub, and the `.qs` property will be set to something like `{ token: token }`.  
I tried reconfiguring the `SignalRModule` on the fly after login, but still the `SignalR` object being injected is configured with the static configuration.
How are you supposed to change your config with non-static values?

**Comment by HNeukermans** [comment]
Hey shaulbehr,

Indeed, that is true. You can use SignalR.connect() method.  I added a section to the readme about this topic.
Regarding the qs issue: indeed good point. qs should support dynamic values.
Going to make an issue for that

**Comment by HNeukermans** [comment]
fixed in v1.0.9

**Comment by shaulbehr** [comment]
I think you meant 1.0.7, no?
