### ISSUE TITLE
@angular/core has no exported member 'Version' and 'NgProbeToken'

### ISSUE THREAD

**Issue by maruthi-menlo** [HNeukermans/ng2-signalr#21]
Hi Team,

I'm using ng2-signalr in my project, able to get the below errors when I import the import { SignalRModule, SignalRConfiguration } from 'ng2-signalr'; in app.module.ts file.

Error:
node_modules/@angular/core/index"' has no exported member 'Version'. 
node_modules/@angular/core/index"' has no exported member 'NgProbeToken'. 

Please let me know how to resolve those typing issues in my project.

FYI.. I'm using below dependencies and dev dependencies using in my package.json

"dependencies": {
    "@angular/common": "2.2.1",
    "@angular/compiler": "2.2.1",
    "@angular/compiler-cli": "2.2.1",
    "@angular/core": "2.2.1",
    "@angular/forms": "2.2.1",
    "@angular/http": "2.2.1",
    "@angular/platform-browser": "2.2.1",
    "@angular/platform-browser-dynamic": "2.2.1",
    "@angular/platform-server": "2.2.1",
    "@angular/router": "^3.4.8",
    "@ionic/storage": "1.1.6",
    "@ngrx/store": "^2.0.1",
    "ionic-angular": "2.0.0-rc.4",
    "ionic-native": "2.2.11",
    "ionicons": "3.0.0",
    "moment": "^2.17.0",
    "ng2-signalr": "^1.0.6",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.26"
  },
  "devDependencies": {
    "@ionic/app-scripts": "^1.0.1",
    "@types/jasmine": "^2.5.38",
    "@types/node": "^6.0.49",
    "angular-cli": "^1.0.0-beta.22-1",
    "awesome-typescript-loader": "^3.0.0-beta.9",
    "codelyzer": "^2.0.0-beta.1",
    "gulp": "^3.9.1",
    "gulp-concat": "^2.6.1",
    "istanbul-instrumenter-loader": "^0.2.0",
    "jasmine-core": "^2.5.2",
    "jasmine-spec-reporter": "^2.7.0",
    "json-loader": "^0.5.4",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.0.2",
    "karma-mocha-reporter": "^2.2.1",
    "karma-phantomjs-launcher": "^1.0.2",
    "karma-remap-coverage": "^0.1.3",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-webpack": "^1.8.0",
    "phantomjs-prebuilt": "^2.1.13",
    "raw-loader": "^0.5.1",
    "source-map-loader": "^0.1.5",
    "ts-helpers": "^1.1.2",
    "ts-node": "^1.7.0",
    "tslint": "^4.0.2",
    "tslint-loader": "^3.3.0",
    "typescript": "^2.0.9",
    "webpack": "~2.1.0-beta.25",
    "xml2js": "^0.4.17"
  }

**Comment by maruthi-menlo** [comment]
@HNeukermans Please respond to this post. Please let me know if you need any other information. Thanks in advance.

**Comment by HNeukermans** [comment]
Are you sure this error is related to ng2-signalr, because the error says nothing about it.
The error refers to the index file inside @maruthi-menlo angular/core/index not exporting a Version member. Can you do a double check by doing a complete reinstall of all packages. Also check the version of your tsc !!

**Comment by maruthi-menlo** [comment]
@HNeukermans After changing the angular versions the issue has been resolved. Thanks for your time.

**Comment by HNeukermans** [comment]
My pleasure @maruthi-menlo.

Glad you like the library.
