### ISSUE TITLE
Expose connection Id

### ISSUE THREAD

**Issue by diegohoyos** [HNeukermans/ng2-signalr#24]
In some cases we need to use the connection id to send it to server api.

**Comment by kkocabiyik** [comment]
The server always knows the connectionid from the context. Context.ConnectionId

**Comment by diegohoyos** [comment]
True if you call the hub. But if you need send the connection id to api controller you need to take it from client.

**Comment by HNeukermans** [comment]
It is something I will add, if I find the time.
In the meantime, as a workaround, you can always try to cast connection as type any, and from there you have access to the orignal javascript object.

untested code: 

```
let jConnection = <any> connection;
jConnection .connection ....
```
Let me know if it works for you

**Comment by HNeukermans** [comment]
added in v1.0.8
