### ISSUE TITLE
Multiple Hub Support

### ISSUE THREAD

**Issue by kkocabiyik** [HNeukermans/ng2-signalr#25]
Does the module support multiple hubs?

**Comment by HNeukermans** [comment]
Yes, you can using 2 connections.

1.  signalr.connect({ hubName : 'xxxx' });
2.  signalr.connect({ hubName : 'yyyy' });

The module configuration contains the default hubname. This means if you don't specify options parameter to singalr.connect() method, the properties from the module configuration will be used. To override the defaults you have to provide options parameter to singalr.connect( { hubName: 'xxx' } );  method.

You can find it in the [code](https://github.com/HNeukermans/ng2-signalr/blob/3ad78389c3d644e7b0fb6c31a0f98823d2900bce/src/connection/connection.options.ts#L10)
and here the [merge](https://github.com/HNeukermans/ng2-signalr/blob/b925b294da3c6f12b9052e140e991e9ab15b49ff/src/signalr.ts#L27)  happens:

**Comment by MarkDeVerno** [comment]
@HNeukermans It seems to me that the multiple connections are being made using your example, or am I misunderstanding the code?

**Comment by HNeukermans** [comment]
Indeed, in the demo app, you can find how to create mutliple connections. More specifically look into the 
Groups page.
