### ISSUE TITLE
Request to add a cpmplete demo with ASP.Net MVC with signalR

### ISSUE THREAD

**Issue by AbrarJahin** [HNeukermans/ng2-signalr#26]
Hi,
This example is great-
http://ng2-signalr-webui.azurewebsites.net/dashboard/element

But, it will be even better if you add an example with `ASP.Net Core/MVC`, `Angular2` and `ng2-signalR` and share the code with us (in Github) so that we can run and test that.

That will make this repo more useful because currently, we are facing some difficulties in connecting signalR.

So, if you make an example, that would be great and a great help for developers 👍 and that will make this repo a great repo because Angular2 has not a complete SignalR library like this 🥇 

Think you get me @HNeukermans 💯

**Comment by HNeukermans** [comment]
both example frontend & backend are open source:
[frontend](https://github.com/HNeukermans/ng2-signalr.demo.webui.systemjs)
[backend](https://github.com/HNeukermans/ng2-signalr.demo.backend)

**Comment by AbrarJahin** [comment]
Thanks @HNeukermans 

Frankly speaking, I am relatively new in Angular and signalR.

So, if everything in the same project, that would be better for me.

Can I have that kind of example @HNeukermans , please?

**Comment by todthomson** [comment]
@AbrarJahin consider forking the repo and work out how to do it and add that yourselves and then send a PR? 😀

**Comment by AbrarJahin** [comment]
Sure, NP. Thanks @HNeukermans
