### ISSUE TITLE
Usage in a service

### ISSUE THREAD

**Issue by MarkDeVerno** [HNeukermans/ng2-signalr#27]
I'd like my components to get their data from a service, and be ignorant where that data comes from.  My service exposes a BehaviorSubject<T> that these components listen to.  This makes it possible to send out updates through multiple mediums; like http and signalr.  What's through me off is the second recommended way of working with this library (injection with activated routes), since this will be in a service.  

Maybe I'm overthinking this, but what would be your recommend approach?

**Comment by DaveMonag** [comment]
```
  private _Connection: SignalRConnectionBase;
  private _OnReceiveMessage: BroadcastEventListener<Message>
  public messageSubject: Subject<any> = new Subject<any>();

  constructor(private _signalR: SignalR) {
    console.log(this._signalR);
    this._OnReceiveMessage = new BroadcastEventListener<Message>("NotifyUser");
    this.setup();
  }

  setup(): Promise<any> {
    var p = new Promise((resolve, reject) => {
      // Initialise connection, and execute function once connected

      this._signalR.connect().then(connection => {
        this._Connection = connection;
        // Start the connection
        connection.start();
        // Subscribe to the event listener and callback when new message received
        this._OnReceiveMessage
          .subscribe(p => {
            console.log(p);
            this.messageSubject.next(p)
          });
        // Start listening to listener
        this._Connection.listen(this._OnReceiveMessage);
        // Resolve empty to resolve P - no need to pass any parameters
        resolve();
      })
    });
    // return to tell anything awaiting promise that setup has finished
    return p;
  }
```

As I've not used routing in my project, so I've done it something like this. I've actually had to change my ng2-signalr module a bit for it to work for me, so this service might be missing something. Sounds like what you want though. Also I'm fairly new to this, so sorry if this is bad quality/not what you were looking for.

**Comment by MarkDeVerno** [comment]
I'm not able to get this to build due _Error: No provider for Function!_.  This sounds related to #14.
What should my module.ts look like?

**Comment by DaveMonag** [comment]
As of the current version it should look like this:
```
import { SignalRModule } from 'ng2-signalr';
import { SignalRConfiguration } from 'ng2-signalr';

const config = new SignalRConfiguration();
config.hubName = 'Ng2SignalRHub';
config.qs = { user: 'donald' };
config.url = 'http://ng2-signalr-backend.azurewebsites.net/';

@NgModule({
  imports: [ 
    SignalRModule.configure(config)
  ]
})
```
But a pull request that changes this slightly should be about to go through, so watch out for that. 
Whats the full error?

**Comment by MarkDeVerno** [comment]
Think I'm ok now.  I've implemented the #28 changes for issue #14.  The error seemed to be caused by putting SignalR and SignalRConfiguration in providers.

**Comment by HNeukermans** [comment]
If you want to wrap the connection inside a service, you can always inject Signalr in your service and then do the signalr.connect() there.

**Comment by fensterputzer** [comment]
Hi there,
I´m actually having similar problems by using the code from DaveMonag...
When logging the injected SignalR object, this is the result:

![unbenannt](https://cloud.githubusercontent.com/assets/26739233/24402230/ec51c476-13b7-11e7-8d52-257019740994.PNG)

So I guess the DI doesn't as it should. I get the following error output:

![unbenannt](https://cloud.githubusercontent.com/assets/26739233/24402428/db78bd3e-13b8-11e7-9867-2e6645e609a5.PNG)



Thanks in advance!

**Comment by HNeukermans** [comment]
The recommended approach is to create the connection inside a resolver.
It is explained in the readme.


`/ 1. if you want your component code to be testable, it is best to use a route resolver and make the connection there
import { Resolve } from '@angular/router';
import { SignalR, SignalRConnection } from 'ng2-signalr';
import { Injectable } from '@angular/core';

@Injectable()
export class ConnectionResolver implements Resolve<SignalRConnection> {

    constructor(private _signalR: SignalR)  {

    resolve() {
        console.log('ConnectionResolver. Resolving...');
        return this._signalR.connect();
    }
}

// 2. use the resolver to resolve 'connection' when navigation to the your page/component
import { Route } from '@angular/router';
import { DocumentationComponent } from './index';
import { ConnectionResolver } from './documentation.route.resolver';

export const DocumentationRoutes: Route[] = [
	{
		path: 'documentation',
    component: DocumentationComponent,
     resolve: { connection: ConnectionResolver }
	}
];

// 3. then inside your component
 constructor(
    private route: ActivatedRoute) {

  }

  ngOnInit() {
    this.connection = this.route.snapshot.data['connection'];
 }`

**Comment by DaveMonag** [comment]
How have you changed from my example? Can't really diagnose without seeing the code. Looks like you've used "_this" as "this" so something you've done with that is probably the problem, and also you're logging "SignalR" (the type) rather than "_signalr" (the injected service) by the look of it.

**Comment by fallXone** [comment]
I seem to be having the same issue, where angular actually isn't injecting the SignalR Service, it's giving the actual class instead and wants it to be newed up via the constructor. I'm seeing the exact same issue as @fensterputzer above. Any thoughts on this?
