### ISSUE TITLE
Adapt to angular library starter - AOT compat

### ISSUE THREAD

**Issue by HNeukermans** [HNeukermans/ng2-signalr#30]
For the sake of getting this library AOT compatibel, ng2-signalr must be adpated to the project structure explained in [angular library starter](https://github.com/robisim74/angular-library-starter)

or this one:

[angular library starter](https://github.com/manekinekko/angular-library-starter)

**Comment by HNeukermans** [comment]
work in progress... :-)

**Comment by lexyfeito** [comment]
is this the reason i am getting this error when i try to build?

" Error encountered resolving symbol values statically. Calling function 'SignalRModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule"

**Comment by HNeukermans** [comment]
yes. 
fixed in v2.0.0
