### ISSUE TITLE
Need to send "Origin" header when connecting from JavaScript to avoid CORS problems

### ISSUE THREAD

**Issue by shaulbehr** [HNeukermans/ng2-signalr#31]
Hi,
My SignalR host is an Azure App Service.  The CORS behavior seems to be different from other hosts, in that if you don't explicitly send an "Origin" header in the connection request, it does not respond with an "Access-Control-Allow-Origin" header, and the browser spits out a CORS error.
Is there some way to do this in the current release, or is that a new feature?

**Comment by HNeukermans** [comment]
I think you need to solve this issue, pure server side.
check my signalr backend. Also hosted on azure and it works. [backend](https://github.com/HNeukermans/ng2-signalr.demo.backend)

**Comment by DaveMonag** [comment]
Can second that. Should look something like this [http://www.cmarix.com/wp-content/uploads/2016/07/Startup.png](url)

**Comment by shaulbehr** [comment]
Thanks, will do.

**Comment by shaulbehr** [comment]
Hi,
Still banging my head on this, and no joy.  Here's what I've done:

1. On Azure, set CORS to allow origin "*"
2. Copied your code from the backend demo project into my Startup class (see attached)
3. Added a section to web.config:
/// <system.webServer>
   <httpProtocol>
     <customHeaders>
       <add name="Access-Control-Allow-Origin" value="*" />
       <add name="Access-Control-Allow-Methods" value="GET,PUT,POST,DELETE,OPTIONS" />
       <add name="web-config-was-read" value="true" />
     </customHeaders>
   </httpProtocol>
 </system.webServer>
```
4. In my Authentication provider, call `SetCorsPolicy()`:
```
       private static void SetCorsPolicy(IOwinContext owinContext)
        {
            owinContext.Response.Headers.Add("Access-Control-Allow-Origin", new[] { "*" });
            owinContext.Response.Headers.Add("SetCorsPolicyCalled", new[] { "true" });
            owinContext.Response.Headers.AppendCommaSeparatedValues("Access-Control-Allow-Headers", "Authorization",
                "Content-Type", "Location", "Date", "loginOnly", "GoogleToken", "CleverToken", "EEToken", "LDAPToken",
                "ADToken", "ShardKey", "UserId", "StudentId", "TeacherId", "ClassId", "UserGroupId", "SchoolId",
                "UserGroupOrganizationId");
            owinContext.Response.Headers.AppendCommaSeparatedValues("Access-Control-Request-Headers", "Authorization",
                "Content-Type", "loginOnly", "GoogleToken", "CleverToken", "EEToken", "LDAPToken", "ADToken", "ShardKey",
                "UserId", "StudentId", "TeacherId", "ClassId", "UserGroupId", "SchoolId", "UserGroupOrganizationId");
            owinContext.Response.Headers.AppendCommaSeparatedValues("Access-Control-Expose-Headers", "Authorization",
                "Content-Type", "Location", "Date");
            owinContext.Response.Headers.AppendCommaSeparatedValues("Access-Control-Allow-Methods", "OPTIONS", "GET",
                "POST", "PUT", "DELETE");
            owinContext.Response.Headers.AppendCommaSeparatedValues("Access-Control-Request-Methods", "OPTIONS", "GET",
                "POST", "PUT", "DELETE");
        }
```
My connection to SignalR returns HTTP200 as before, but there is still no "Access-Control-Allow-Origin" header.  I do, however, have "web-config-was-read" and "SetCorsPolicyCalled" headers, which shows that my code is, in fact, being called - but the "Access-Control-Allow-Origin" header is specifically being stripped out.

When I add an "Origin" header to my SignalR request, however, I do get back the "Access-Control-Allow-Origin" header.

What am I doing wrong?

And - as a shortcut - is it possible somehow to get the ng2-signalr library to send that "Origin" header?

[App_Start.zip](https://github.com/HNeukermans/ng2-signalr/files/870764/App_Start.zip)

**Comment by shaulbehr** [comment]
Incidentally, @HNeukermans , I added that line:
```
appBuilder.SetDataProtectionProvider(new MachineKeyProtectionProvider());
```
Made no difference.
I found someone else having a related issue [here](https://github.com/Azure/azure-webjobs-sdk-script/issues/620), which they resolved by removing the CORS configuration in Azure (my step 1 above), and I followed suit - also made no difference... 

The only thing that seems to work is sending an "Origin" header in the request.

**Comment by shaulbehr** [comment]
[Problem solved](http://stackoverflow.com/a/43040534/7850) on the Azure side.
