### ISSUE TITLE
ng2-signalr can't be compiled

### ISSUE THREAD

**Issue by askdong** [HNeukermans/ng2-signalr#34]
Hi,

E:\opensource-project\temp-aspnet\angularcli\d3-ng2-demo-master>ng serve
** NG Live Development Server is running on http://localhost:4200 **
Hash: fb506f72cd9ce73e44ce
Time: 35399ms
chunk    {0} main.bundle.js, main.bundle.js.map (main) 51.7 kB {2} [initial] [rendered]
chunk    {1} styles.bundle.js, styles.bundle.js.map (styles) 129 kB {3} [initial] [rendered]
chunk    {2} vendor.bundle.js, vendor.bundle.js.map (vendor) 3.07 MB [initial] [rendered]
chunk    {3} inline.bundle.js, inline.bundle.js.map (inline) 0 bytes [entry] [rendered]

ERROR in E:/opensource-project/temp-aspnet/angularcli/d3-ng2-demo-master/node_modules/ng2-signalr/lib/testing/helpers/activated.route.mock.d.ts (4,22)
: Class 'ActivatedRouteMock' incorrectly implements interface 'ActivatedRoute'.
  Property 'paramMap' is missing in type 'ActivatedRouteMock'.
webpack: Failed to compile.

E:\opensource-project\temp-aspnet\angularcli\d3-ng2-demo-master>npm ls ng2-signalr
d3-ng2-demo@0.1.1 E:\opensource-project\temp-aspnet\angularcli\d3-ng2-demo-master
+-- UNMET PEER DEPENDENCY @angular/core@4.0.0 -> E:\opensource-project\temp-aspnet\angularcli\d3-ng2-demo-master\node_modules\.4.0.0@@angular\core
`-- ng2-signalr@1.0.9  -> E:\opensource-project\temp-aspnet\angularcli\d3-ng2-demo-master\node_modules\.1.0.9@ng2-signalr

Thank you!

**Comment by HNeukermans** [comment]
There seems ti be an unmet peer dependency UNMET PEER DEPENDENCY @angular/core@4.0.0
maybe that is causing the problem

**Comment by DaveMonag** [comment]
Looks like the Angular developers introduced something called paramMap a few days ago: https://github.com/angular/angular/commit/a755b715ed5566a6796bc538653362edab8f74d4
You might need to update your ActivatedRouteMock class @HNeukermans

**Comment by HNeukermans** [comment]
Nice tip @DaveMonag.
in the meantime i just pusblished v2.0.0.
Hopefully this fixes all AOtT issues so far...

**Comment by HNeukermans** [comment]
are you comiling against angular 4.0.0 ?
As a workaround I think you can remove the 'implements ActivatedRoute' in the activated.route.mock.d.ts file

so instead of
ActivatedRouteMock implements ActivatedRoute
make it
ActivatedRouteMock

In the meantime I will fix the issue ...

**Comment by askdong** [comment]
Yes, I compiled against angular 4.0.0.
Now, It can be compiled OK after I upgrade to version 2.0.2.

thank you! 
also thanks to @DaveMonag !
