### ISSUE TITLE
There's a big error in your package

### ISSUE THREAD

**Issue by chachaxw** [HNeukermans/ng2-signalr#35]
![big error](http://7xqacx.com1.z0.glb.clouddn.com/big-problem.png)
💔 Classs 'ActivatedRouteMock' incorrectly implements interface 'ActivatedRoute', Because property 'paramMap : Observable<ParamMap>' and 'queryParamMap : Observable<ParamMap>' are missing in 'ActivatedRouteMock'. 💔 
Please fix this bug, thanks.

**Comment by HNeukermans** [comment]
Thx @chachaxw,

will fix by tonight

**Comment by HNeukermans** [comment]
it seems upgrading to v2.0.2 does the trick..
