### ISSUE TITLE
dynamic url config at module level

### ISSUE THREAD

**Issue by morwn** [HNeukermans/ng2-signalr#42]
Hey,
As I  see we need to supply function that returns SignalRConfiguration object,
my case contain read signalr url from json file(which I prefer doing in APP_INITIALIZER),
so it necessary to override 'this':
SignalRModule.forRoot(createConfig.bind(this)),
or call some service(which inject http service),
or maybe you can think about an alternative way?

**Comment by HNeukermans** [comment]
you can pass in IConnectionOptions object to Signalr.connect() method. IConnectionOptions object has ability to set the url of the hub.

**Comment by morwn** [comment]
there is no way to set configuration at module level?

**Comment by HNeukermans** [comment]
maybe, another option is to use DefinePlugin to inject the variable @designtime
