### ISSUE TITLE
Multiple messages not supported

### ISSUE THREAD

**Issue by TheOnlyMarv** [HNeukermans/ng2-signalr#43]
If Iam listening to an event eg. "MessageReceived", then it returns just the first argument of the message.
At `casted = <T> args[0];` its smarter to assign the whole array: `casted = args;`.
I tried it and for me it works perfectly.
Now we can receive a message with a tuple as array.

**Comment by HNeukermans** [comment]
To better understand wath you mean, 
could you show me the server code that emits such 'messages' ?

**Comment by iMav** [comment]
Server: `Clients.All.ReceiveMessage ( "first", "second", "third");`

Now if iam listen to `connection.listenFor('ReceiveMessage')`, it's just returns me "first".

**Comment by HNeukermans** [comment]
Ok - got it. Will add this is a future release.

**Comment by HNeukermans** [comment]
helas this is not possible.
Reason is that observer.next(....) only has 1 argument to call. 
you can work around this problem by sending changing code server side from
Clients.All.ReceiveMessage ( "first", "second", "third");
to
Clients.All.ReceiveMessage ( new List<string>("first", "second", "third"));
