### ISSUE TITLE
Build warning with 2.0.3

### ISSUE THREAD

**Issue by ogrim** [HNeukermans/ng2-signalr#46]
I got the following warning building with Angular CLI:

`Warning: Can't resolve all parameters for SignalR in C:/work/redacted/node_modules/ng2-signalr/src/services/signalr.d.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x
`

Everything is working fine, just flagging this if you are not aware 😃 

I am using Angular 4.0.1, Angular CLI is 1.0.0, and ng2-signalr is 2.0.3 ✨ .

**Comment by HNeukermans** [comment]
Hi  @ogrim,

thx for letting me know.

**Comment by sam-s4s** [comment]
Ah good, was about to create an issue for this :D

**Comment by DaveMonag** [comment]
@HNeukermans Any progress on what's causing this?

**Comment by HNeukermans** [comment]
checked yesterday with latest @angular/cli (1.1.2) and ng2-signalr v2.0.6.
Could not reproduce this warning.

**Comment by sam-s4s** [comment]
Yep, still dead for me :( I updated to the latest version (2.0.6, from 2.0.3).

It dies during the AoT build... eg... "ngc -p tsconfig_aot.json".

Warning: Can't resolve all parameters for SignalR in C:/s4s/crm2/crm2/a2-dev/node_modules/ng2-signalr/src/services/signalr.ts: ([object Object], [object Object], ?). This will become an error in Angular v5.x

**Comment by davidgabrichidze** [comment]
I'm was getting same warning in my project. 

After reading this [brief description](https://www.lucidchart.com/techblog/2017/04/20/removing-roadblocks-move-angular-4/) about 4.x upgrade, I've removed  `@Injectable()` from some classes and it fixed. and yes, it still works :)

**Comment by DOMZE** [comment]
@sam-s4s is right.

The SignalR is an Injectable class (@Injectable). It has 3 parameters which the 3rd cannot be inferred because it's of type Function.

@HNeukermans there are ways to go around this. What would be your prefered way?

**Comment by frank7huysen** [comment]
I'm also running into this issue. Is there already a workaround for this?

**Comment by iTwangcj** [comment]
![image](https://user-images.githubusercontent.com/7961076/28963470-cb76c230-793b-11e7-818e-441f2b8e4624.png)
