### ISSUE TITLE
Error in latest version

### ISSUE THREAD

**Issue by rocodesign** [HNeukermans/ng2-signalr#47]
I just installed the latest version

Here are the version in my package json
"expose-loader": "^0.7.3",
"jquery": "^3.2.1",
"signalr": "^2.2.1",
"ng2-signalr": "^2.0.3",

I'm trying to configure inside a module:
```
import { SignalRModule, SignalRConfiguration } from 'ng2-signalr';

const config = new SignalRConfiguration();
config.hubName = 'Ng2SignalRHub';
config.qs = { user: 'donald' };
config.url = 'http://ng2-signalr-backend.azurewebsites.net/';

@NgModule({
  imports: [
     ...
    SignalRModule.configure(config)
  ],
```
**ERROR in ..../src/app/apps/apps.module.ts (63,19): Property 'configure' does not exist on type 'typeof SignalRModule'**

this is my d.ts

```
import { ModuleWithProviders, NgZone } from '@angular/core';
import { SignalR } from '../services/signalr';
import { SignalRConfiguration } from '../services/signalr.configuration';
export declare function createSignalr(configuration: SignalRConfiguration, zone: NgZone): SignalR;
export declare class SignalRModule {
    static forRoot(getSignalRConfiguration: Function): ModuleWithProviders;
    static forChild(): ModuleWithProviders;
}
```

in signalr-module.js

```
SignalRModule.forChild = function () {
        throw new Error("forChild method not implemented");
    };
```
So I cannot use that too.

I tried to import also at the root level but I don't really need it there.
Anything I'm doing wrong?

**Comment by HNeukermans** [comment]
you need to use forRoot().
You can find the solution in the readme.

**Comment by rocodesign** [comment]
Thanks @HNeukermans, I missed the // v2.0.0 comment, works now.
