### ISSUE TITLE
'jquery.js' is missing.

### ISSUE THREAD

**Issue by almgwary** [HNeukermans/ng2-signalr#51]
Signalr failed to initialize. Script 'jquery.js' is missing. Please make sure to include jquery script.
    at `getJquery (signalr-module.js:31)`

**Comment by HNeukermans** [comment]
Hi @almgwary,
to fix this error you need to include the jquery script.

**Comment by almgwary** [comment]
@HNeukermans 
why library not include it dependency it self ? 
i am using Ionic-2 i tried to include it in my component but it doesn't work
also i included it in index.html it doesn't work too .

**Comment by almgwary** [comment]
i have to solve this task urgently .
i have a deliverable this week

**Comment by almgwary** [comment]
**Ionic version:**  (check one with "x")
[ ] **1.x**
[x ] **2.x**
[ ] **3.x**

 
**Current behavior:**

I need to use [this ng2-signalr library ](https://github.com/HNeukermans/ng2-signalr) and ng2-signalr need to include  [these 2 JS files](https://github.com/HNeukermans/ng2-signalr#detailed-webpack-install) .
i followed all steps carefully and add ng2-signalr module with no problem .
when inject library in component i have the issue with missing the previous files 
  

i tried to include them in index.html but it didn't work 
```
  <script  src="https://code.jquery.com/jquery-3.2.1.min.js" ></script>
  <script src="https://ajax.aspnetcdn.com/ajax/signalr/jquery.signalr-2.2.1.min.js"  ></script>

```
i tried them too inside my component but it didn't work too 
```
import * as $ from 'jquery';
window['jQuery'] = $;
import 'signalr/jquery.signalR.js';
```

this is urgent i have delevrable i need to use SignalR ASAP

**Comment by almgwary** [comment]
**Fixed** i need to add this in my component 
```
import 'expose-loader?jQuery!jquery';
import '../node_modules/signalr/jquery.signalR.js';
```

**Comment by mfp22** [comment]
I just needed to stop getting this error for my test to run. So I used a solution for jest similar to https://github.com/facebook/jest/issues/708 but with this in `test-env.ts` instead:
```
import * as $ from 'jquery';
$.hubConnection = {};
global.$ = global.jQuery = $;
```

**Comment by DRNPerera** [comment]
> **Fixed** i need to add this in my component
> 
> ```
> import 'expose-loader?jQuery!jquery';
> import '../node_modules/signalr/jquery.signalR.js';
> ```

exactly where to put these imports?

**Comment by almgwary** [comment]
@DRNPerera  inside you component
