### ISSUE TITLE
Connection status never returns "connected"

### ISSUE THREAD

**Issue by DaveMonag** [HNeukermans/ng2-signalr#52]
I've noticed that when running
`this.connection.status.subscribe(status => console.log(status)); `
You only seem to get back "stateChanged", "disconnected" and "recieved", but never "connected" when the connection is established. Is this expected behavior? If so, how am I supposed to base something off the knowledge that it is connected? For example, I just want an icon in the top left that shows green when SignalR is connected to a hub, and red when not connected. Is this possible?

**Comment by HNeukermans** [comment]
This is expected behavior: [read](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/handling-connection-lifetime-events ).
Understanding the signalr connection lieftime is the most easy... bc there is a difference between physical and logical connections.

The best approximation is to show a red dot when the disconnected event is raised. In all other cases you show the green button.

**Comment by DaveMonag** [comment]
What about calls though? If I want to invoke a method on the SignalR Hub immediately on opening the webpage, it will fail because the SignalR connection did not exist yet. Is there no event driven way to do this so it waits for the connection to establish THEN invokes the call without using the route resolver method?

**Comment by HNeukermans** [comment]
Do you mean Signalr.connect().then() ?

**Comment by HNeukermans** [comment]
Next to Signalr.connect(), 
I will also provide a Signalr.createConnection() which gives back a connection object that allows you to subscribe to the status observable.

**Comment by HNeukermans** [comment]
fixed.
iin addition to writing
 `this._signalR.connect().).then((c) => { ....`
You can now write 
 ` let conx = this._signalR.createConnection(); `
`conx.status.subscribe((s) => console.warn(s.name));`
  ` conx.start().then((c) => { ....`

**Comment by DaveMonag** [comment]
This code isn't live yet is it?
