### ISSUE TITLE
Can't subscribe to event with no arguments

### ISSUE THREAD

**Issue by R2D221** [HNeukermans/ng2-signalr#54]
With an event like this in server side:

    Clients.All.hello();

This event will never raise on the client:

    const hello = new BroadcastEventListener('hello');
    this.connection.listen(hello);
    hello.subscribe(() => {
        alert("Hello");
    });

**Comment by HNeukermans** [comment]
Hi @R2D221,

Interesting .. if this is the case, this needs fixing.

Thanks for posting

**Comment by HNeukermans** [comment]
fixed in build 2.04.

let me know if it doesnt work for you
