### ISSUE TITLE
2.0.6 broke tests

### ISSUE THREAD

**Issue by MaxMaes** [HNeukermans/ng2-signalr#61]
The current npm package is at 2.0.6 but it would be nice to know what changed in between updates.

With the 2.0.4 -> 2.0.6 update, my unit tests don't work anymore when I'm providing SignalR. In order for all dependencies to be provided, I provide SignalRConfiguration, NgZone and the JConnectionStub as a function, but it can't resolve the latter since latest update:

 Can't resolve all parameters for SignalR: ([object Object], [object Object], ?).

**Comment by MaxMaes** [comment]
![image](https://user-images.githubusercontent.com/8969390/27130954-e70340ce-5108-11e7-8f36-2bf5b15e351c.png)

**Comment by HNeukermans** [comment]
@MaxMaes,

thx for posting.
Will look into it.

Can you show me your testing code?
Does you production code still work?

**Comment by HNeukermans** [comment]
I've updated the readme for v2.0.6
