### ISSUE TITLE
An error in the ionic2 project

### ISSUE THREAD

**Issue by ejiyuan** [HNeukermans/ng2-signalr#64]
Runtime Error
Uncaught (in promise): Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\Documents\visual studio 2017\Projects\UDahuo\UDahuo.App\node_modules\ng2-signalr\index.js' at Error (native) Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\Documents\visual studio 2017\Projects\UDahuo\UDahuo.App\node_modules\ng2-signalr\index.js' at Error (native) at Object.714 (http://localhost:8100/build/2.main.js:16092:7) at __webpack_require__ (http://localhost:8100/build/main.js:48:30) at Object.727 (http://localhost:8100/build/2.main.js:16385:70) at __webpack_require__ (http://localhost:8100/build/main.js:48:30) at Object.568 (http://localhost:8100/build/2.main.js:10:64) at __webpack_require__ (http://localhost:8100/build/main.js:48:30) at http://localhost:8100/build/main.js:81470:10 at t.invoke (http://localhost:8100/build/polyfills.js:3:8971) at Object.onInvoke (http://localhost:8100/build/main.js:4625:37) at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)
Stack
Error: Uncaught (in promise): Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\Documents\visual studio 2017\Projects\UDahuo\UDahuo.App\node_modules\ng2-signalr\index.js'
    at Error (native)
Error: Module build failed: Error: ENOENT: no such file or directory, open 'E:\Documents\visual studio 2017\Projects\UDahuo\UDahuo.App\node_modules\ng2-signalr\index.js'
    at Error (native)
    at Object.714 (http://localhost:8100/build/2.main.js:16092:7)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.727 (http://localhost:8100/build/2.main.js:16385:70)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at Object.568 (http://localhost:8100/build/2.main.js:10:64)
    at __webpack_require__ (http://localhost:8100/build/main.js:48:30)
    at http://localhost:8100/build/main.js:81470:10
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8971)
    at Object.onInvoke (http://localhost:8100/build/main.js:4625:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)
    at c (http://localhost:8100/build/polyfills.js:3:13190)
    at Object.reject (http://localhost:8100/build/polyfills.js:3:12546)
    at NavControllerBase._fireError (http://localhost:8100/build/main.js:44280:16)
    at NavControllerBase._failed (http://localhost:8100/build/main.js:44268:14)
    at http://localhost:8100/build/main.js:44323:59
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8971)
    at Object.onInvoke (http://localhost:8100/build/main.js:4625:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:8911)
    at r.run (http://localhost:8100/build/polyfills.js:3:4140)
    at http://localhost:8100/build/polyfills.js:3:13731
Ionic Framework: 3.3.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.2
Angular Compiler CLI: 4.1.2
Node: 6.9.5
OS Platform: Windows 10
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.104 Safari/537.36
----------------------------------------------------------------------------------------------------------
my code：
chat.module.ts

import { SignalRModule } from 'ng2-signalr';
import { SignalRConfiguration } from 'ng2-signalr';

@NgModule({
    declarations: [Chat],
    imports: [
        SignalRModule.forRoot(createConfig),
        EmojiPickerComponentModule,
        RelativeTimeModule,
        IonicPageModule.forChild(Chat)
    ],
    exports: [
        Chat
    ],
    providers: [
        ChatService,
        EmojiProvider
    ]
})
export class ChatModule { }
// v2.0.0
export function createConfig(): SignalRConfiguration {
    const c = new SignalRConfiguration();
    c.hubName = 'Ng2SignalRHub';
    c.qs = { user: 'donald' };
    c.url = 'http://ng2-signalr-backend.azurewebsites.net/';
    c.logging = true;
    return c;
}

Chat.ts    
constructor(private signalR: SignalR) {
        signalR.connect().then(connection => {
            console.log(connection.status);
            let onMessageSent$ = connection.listenFor('ON_MESSAGE_SENT');
            
            onMessageSent$.subscribe((chatMessage: ChatMessage) => {
                //this.chatMessages.push(chatMessage);
                console.log(chatMessage);
            });
        });
}

**Comment by HNeukermans** [comment]
He is somehow not finding ng2-signalr/index.js.
Check if it is exists in your node_modules, if yes check if it is required/imported correctly;
Probably it is not imported correctly.

**Comment by ejiyuan** [comment]
![default](https://user-images.githubusercontent.com/7286984/27275601-bda5dc4a-550a-11e7-8e2b-dc693dadee1d.JPG)
