### ISSUE TITLE
noUnusedLocals errors

### ISSUE THREAD

**Issue by saithis** [HNeukermans/ng2-signalr#65]
When we activate noUnusedLocals in our project, we get a bunch of errors in node_modules/ng2-signalr. 
The reason is, that you ship the typescript source files instead of compiled files. 

Could you please change it, so that the npm package only contains the *.d.ts, *.js, *.js.map, *.metadata.json and package.json files?

This would also fix the problem with other compiler options like noImplicitAny, strictNullChecks, etc.

**Comment by HNeukermans** [comment]
need to add .npmignore file
