### ISSUE TITLE
simple demo 

### ISSUE THREAD

**Issue by nadircan** [HNeukermans/ng2-signalr#70]
firstly thanks for this project.

But I could not make this project work. Do you have a simpler working example?

**Comment by italojs** [comment]
are you already see the demo? http://ng2-signalr-webui.azurewebsites.net/

**Comment by nadircan** [comment]
i have seen it. but i confused. I need simple angular-cli app with ng2-signalr

**Comment by HNeukermans** [comment]
[follow this link](https://github.com/HNeukermans/ng2-signalr.demo.webui.ngcli)
