### ISSUE TITLE
Client method calls only getting first parameter

### ISSUE THREAD

**Issue by jmfullerton** [HNeukermans/ng2-signalr#73]
I have an existing hub that calls client methods that have multiple parameters.  I do receive the message except I only receive the first parameter.  The parameters consist of strings, numbers and a complex type. Do you have any examples on how to use your code in this scenario?

**Comment by HNeukermans** [comment]
Currently solution would be to  change server side code to a callback method with only one object that contains all parameters.

**Comment by LastTribunal** [comment]
this is a pain

**Comment by Floyd1256** [comment]
Any updates on this? Changing server side code would be heavy duty and impractical!
Thanks

**Comment by jmfullerton** [comment]
I wound up writing my own angular service component that that defines handlers for the calls coming from the server and makes the connection to the hub.  I created interfaces to define all of the parameters coming from the server for each call coming from the server.  In addition, my angular service defines an observable for each message coming from the server.  When my service component receives a message, it packs the parameters into an object defined by the interfaces I created. It then calls “next” to send the packed parameters  to the subscribers.

I inject my service wherever I need to handle the server sent messages and subscribe to the appropriate observable on the injected service component.  

Doing it this way didn’t require changing any hub or server code.  Hope that helps.

**Comment by thduttonuk** [comment]
Any more updates on this? I'm having to hack it a bit to get it to work. I'm just doing this in the signalr.connection.ts file. To change server side would be a pain.

`      if (args.length === 1) {
                    casted = <T>args[0];
                }else if (args.length > 0){
                    casted = Object.assign(<any>{}, args)
                }`

**Comment by jmfullerton** [comment]
I wound up rolling my on solution which includes basically the following.

I wrote an Angular service that handles all the communication to and from the hub.   I then created Subjects as members of the service for each method that calls into the client.  Next I defined a typescript interface for the data contained in each message going to the client.

When the service receives a message from the hub it repacks the individual fields into a single object defined by one of the interfaces discussed above.

Then the service takes the packed data and makes a call like  this.onMessage.next(data);

Anywhere in the app that needs to handle the message(s) I inject the service then subscribe to the service Subjects to get notified of messages coming from the hub.  The client of the service can then unpack the data using the interface defined members.

Hope that helps.



Sent from Mail for Windows 10

**Comment by thduttonuk** [comment]
@HNeukermans having a look into updating the solution. We could add a param to listenFor 

`public listenFor<T>(event: string, onlyFirstParam: boolean = true): BroadcastEventListener<T> { ... }`

OR 
a new function called ListenForAll that would return all the params

I have both working locally, not sure what is best to do a pull request for.

**Comment by Floyd1256** [comment]
@thduttonuk good suggestion, I believe having a new function would be the 'cleaner' fix . What do you guys think?

**Comment by Verri8** [comment]
Any information for following problem?

**Comment by salih0313** [comment]
any improvement on this issues?

**Comment by thduttonuk** [comment]
Fixed in 6.1.0

**Comment by chanashochat** [comment]
please use listenForRaw,
it will get all parameters
