### ISSUE TITLE
this._signalR.connect is not a function

### ISSUE THREAD

**Issue by prasadmamidi7** [HNeukermans/ng2-signalr#76]
Hi
I am getting following error while running the application.
this._signalR.connect is not a function

Note:
- I am using angular cli
- I have executed "npm install ng2-signalr jquery signalr --save". and included the javascript reference in package.json scripts [] arrary
- i have crossed checked the Javascript libraries for jquery and singalR are available under node_module

but still i am getting the error. Can you please let me know how to resolve this issue.

**Comment by VitalyKuznetsov** [comment]
prasadmamidi7

> Hi
> I am getting following error while running the application.
> this._signalR.connect is not a function

> Note:

> I am using angular cli
> I have executed "npm install ng2-signalr jquery signalr --save". and included the javascript reference in > package.json scripts [] arrary
> i have crossed checked the Javascript libraries for jquery and singalR are available under node_module
> but still i am getting the error. Can you please let me know how to resolve this issue.

Hello. Probably first of all you should create connection in your constructor, something like this:

```
import { SignalR, SignalRConnection } from 'ng2-signalr';

private _conx: SignalRConnection;

constructor(_signalR: SignalR) {
this._conx = _signalR.createConnection();
}
```
and then inside ngOnInit:

```
this._conx.start().then((c) => {
// here the logic: 
// this._conx.invoke(...
// this._conx.listenFor(...
});
```
