### ISSUE TITLE
Transport Issues 

### ISSUE THREAD

**Issue by zhangboli51** [HNeukermans/ng2-signalr#80]
so this is the errors 

> core.es5.js:1020 ERROR Error: Uncaught (in promise): Failed to connect. Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization.
>     at resolvePromise (zone.js:770)
>     at resolvePromise (zone.js:741)
>     at zone.js:818
>     at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:424)
>     at Object.onInvokeTask (core.es5.js:3924)
>     at ZoneDelegate.webpackJsonp.../../../../zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:423)
>     at Zone.webpackJsonp.../../../../zone.js/dist/zone.js.Zone.runTask (zone.js:191)
>     at drainMicroTaskQueue (zone.js:584)
>     at ZoneTask.invoke (zone.js:490)
>     at timer (zone.js:1540)

after I look at the readme.txt 
I tried those:
`transport:ConnectionTransport.none` 
`transport:ConnectionTransport.auto
`
but none of them work  
and console throw this error to me 

> ERROR in C:/Users/bgm3325/Desktop/ng2-signalr.demo/ng2-signalr.demo.webui.ngcli/src/app/app.module.ts (15,33): Property 'none' does not exist on type 'typeof ConnectionTransport'.

also tried 
`c.transport = [ConnectionTransports.webSockets, ConnectionTransports.longPolling];`

but
> 
> ERROR in C:/Users/bgm3325/Desktop/ng2-signalr.demo/ng2-signalr.demo.webui.ngcli/src/app/app.module.ts (14,38): Property 'webSockets' does not exist on type 'typeof ConnectionTransport'.
> 
> ERROR in C:/Users/bgm3325/Desktop/ng2-signalr.demo/ng2-signalr.demo.webui.ngcli/src/app/app.module.ts (14,70): Property 'longPolling' does not exist on type 'typeof ConnectionTransport'.
> 
>

**Comment by DaveMonag** [comment]
Are you on the latest version? They were changed in one version I believe

**Comment by zhangboli51** [comment]
`npm install ng2-signalr jquery signalr --save`

I don't know if I'm on the latest version .  but use that command to install package.

**Comment by HNeukermans** [comment]
have you tried 
`transport:ConnectionTransports.none` (mind the 's'!!!)

**Comment by HNeukermans** [comment]
I think 'transport : auto' is probably not correct. Because following the original signalr documentation 
auto value is not mentioned.  [link to doc](https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-javascript-client). If that is the case this bug need to be corrected !! Can you try `transport : null`  and see if it works?

**Comment by zhangboli51** [comment]
problem solved . I reinstalled ng2-signalr package, and then it works . 
Thanks for help.
