### ISSUE TITLE
Unable to use with Angular 5 as OpaqueToken has been removed

### ISSUE THREAD

**Issue by jinder** [HNeukermans/ng2-signalr#86]
Trying to use this package with Angular 5 doesn't work because it's using OpaqueToken which has been deprecated in 4.0, and completely removed in 5.  Please can you update the usage of this to use InjectionToken instead?

**Comment by HNeukermans** [comment]
Ok. Thx for logging this issue. Will look into this...

**Comment by GiuntaLucas** [comment]
Hi @HNeukermans ,

I'm running into the same issue. 
I'm also highly interested in a fix!

Thank you very much for your response

**Comment by kemmis** [comment]
+1 this is preventing me from updating to angular 5

**Comment by Zerq** [comment]
Yep me too... hope this get resolved soon

**Comment by pbriones** [comment]
@HNeukermans , I've created a PR for this similar to what I'm using now on my project to get this to work. Let me know if there's modifications that needs to be done to make it compliant to this project.

**Comment by mcgri** [comment]
fingers crossed this will be resolved soon. It's a blocker for our project

**Comment by jumaju** [comment]
Hi @HNeukermans,

Thanks for merging, but would be great to update the package on NPM !

**Comment by liri2006** [comment]
Any ETA on publishing to NPM?

**Comment by dipanmehta** [comment]
@liri2006 , I am also waiting for new changes to be published. it breaks my angular 5 migration

**Comment by kemmis** [comment]
+1 would like NPM package update

Thanks!

**Comment by jizza** [comment]
+1 Breaks angular5 migration

**Comment by raschle** [comment]
+1

**Comment by aprotimi** [comment]
+1

**Comment by Muhammad-Soban** [comment]
+1

**Comment by dipanmehta** [comment]
I have make it works using @pbriones solution. I have downloaded his solution and copied src folder into node_modules of an application. It’s a short time patch but before you get specific npm package, you can use it for initial transformation to angular 5

**Comment by SkeletonSkelettron** [comment]
Hi everyone

until this gets fixed in future release, here's temporary workaround fix for Angular5

change **OpaqueToken** to **InjectionToken** in signalr.module.js (path - \node_modules\ng2-signalr\src\services) and signalr-module.js (\node_modules\ng2-signalr\src\modules)
after it everything wokrs fine

**Comment by pbriones** [comment]
@dipanmehta, as said in #92, if you run angular with --aot, it should work fine. I'm using `ng serve --aot --sourcemap` while waiting for the build. --aot on local is pretty fast on ng5. Caveat is that tests dependent on non-aot builds will be broken.

@HNeukermans, would you prefer that we restrict the angular requirements to 5+ and increase your package version to 3.x.x so everyone will be aware that this is a breaking change?

**Comment by joaogomesfairsailcom** [comment]
+1

**Comment by alvarosinmarca** [comment]
Please update support for Angular 5! 
Thanks you.

**Comment by ylibrach** [comment]
@HNeukermans is it possible to release a new package version? The PR to support Angular 5 was merged in weeks ago, we just need a new version to be released through NPM. We can download full sources and use that directly, but obviously that's not ideal.

**Comment by liri2006** [comment]
Its been almost two months now since the fix was merged...

**Comment by dharapvj** [comment]
I forked and compiled and published this library as a temporary measure under different scope.. so that it becomes usable for Angular 5..

please use it as `npm i @dharapvj/ngx-signalr`. It will install v3.0.0 and you will not face the issue of OpaqueToken anymore.

**Comment by jemunk** [comment]
Thanks a lot @dharapvj 
Works beautifully!

**Comment by HNeukermans** [comment]
This issue should be fixed in version 5.0.0

**Comment by carlososiel** [comment]
I update to version `5.0.0-beta.13` and I experimented the same issue. Exist definitive way to use flex-layout with angular 5?
