### ISSUE TITLE
2.1.1 still error incorrectly implements interface 'Resolve<SignalRConnection>'

### ISSUE THREAD

**Issue by namrastanov** [HNeukermans/ng2-signalr#88]
@Injectable()
export class SignalRConnectionResolve implements Resolve<SignalRConnection> {
    constructor(private _signalR: SignalR) { }
    resolve() {
        console.log('SignalRConnectionResolve. Resolving...');
        return this._signalR.connect();
    }
} 

`incorrectly implements interface 'Resolve<SignalRConnection>'.
  Types of property 'resolve' are incompatible.
    Type '() => Promise<ISignalRConnection>' is not assignable to type '(route: ActivatedRouteSnapshot, state: RouterStateSnapshot) => SignalRConnection | Observable<Sig...'.
      Type 'Promise<ISignalRConnection>' is not assignable to type 'SignalRConnection | Observable<SignalRConnection> | Promise<SignalRConnection>'.
        Type 'Promise<ISignalRConnection>' is not assignable to type 'Promise<SignalRConnection>'.
          Type 'ISignalRConnection' is not assignable to type 'SignalRConnection'.
            Property '_status' is missing in type 'ISignalRConnection'.`

with version 2.0.4 get the same error

**Comment by SkeletonSkelettron** [comment]
Hi.
I had same problem, (typescript ver 2.5.3)
change the following classes accordingly and you will succeed

export interface ISignalRConnection {
    private _status;
    private _errors;
    private _jConnection;
    private _jProxy;
    private _zone;
    private _configuration;
    readonly status: Observable<ConnectionStatus>;
    readonly errors: Observable<any>;
    readonly id: string;
    invoke(method: string, ...parameters: any[]): Promise<any>;
    listen<T>(listener: BroadcastEventListener<T>): void;
    listenFor<T>(listener: string): BroadcastEventListener<T>;
    stop(): void;
    start(): Promise<any>;
    private convertTransports(transports);
    private wireUpErrorsAsObservable();
    private wireUpStatusEventsAsObservable();
    private onBroadcastEventReceived<T>(listener, ...args);
    private log(...args);
}


export declare class SignalRConnection implements ISignalRConnection {
    public _status;
    public _errors;
    public _jConnection;
    public _jProxy;
    public _zone;
    public _configuration;
    constructor(jConnection: any, jProxy: any, zone: NgZone, configuration: SignalRConfiguration);
    readonly errors: Observable<any>;
    readonly status: Observable<ConnectionStatus>;
    start(): Promise<ISignalRConnection>;
    stop(): void;
    readonly id: string;
    invoke(method: string, ...parameters: any[]): Promise<any>;
    listen<T>(listener: BroadcastEventListener<T>): void;
    listenFor<T>(event: string): BroadcastEventListener<T>;
    public convertTransports(transports);
    public wireUpErrorsAsObservable();
    public wireUpStatusEventsAsObservable();
    public onBroadcastEventReceived<T>(listener, ...args);
    public log(...args);
}

they are found in node_modules/ng2-signalr

**Comment by tomadj** [comment]
Hello, 

Same problem.

Any official fix ?

**Comment by SkeletonSkelettron** [comment]
Hi, unfortunately, there is no official fix. 
But above workaround works for me.

**Comment by ahlunju** [comment]
you just have to change the import SignalRConnection to ISignalRConnection, 
and change the export class ConnectionResolver implements Resolve<SignalRConnection> to export class ConnectionResolver implements Resolve<ISignalRConnection>

**Comment by HNeukermans** [comment]
If you are using ng v5, you can move to ng2-signalr v3. In version 2.1.1 these props are not supported.

**Comment by Codewizard** [comment]
@ahlunju 's fix worked for me with the latest version.

**Comment by SemVC7** [comment]
@ahlunju fix worked for me as well, using "ng2-signalr": "^5.0.0" & "signalr": "^2.2.3"!

**Comment by HeroSpha** [comment]
@nulayuhz worked for me
