### ISSUE TITLE
AoT compilation

### ISSUE THREAD

**Issue by pdunlop** [HNeukermans/ng2-signalr#9]
Hi,

This library works great, but I can't get it working with AoT compilation.

If it helps, my current work-around is to create my own SignalRModule, which looks like this:
(Please not I have no idea whether this is the correct solution!)

```
import { NgModule, ModuleWithProviders, NgZone, OpaqueToken } from '@angular/core';
import { SignalR, SignalRConfiguration } from 'ng2-signalr';

const SIGNALR_CONFIGURATION = new OpaqueToken('SIGNALR_CONFIGURATION');

export function signalrFactory(zone: NgZone, configuration: SignalRConfiguration): any {
    return new SignalR(configuration, zone);
}

@NgModule({
    providers: [{
        provide: SignalR,
        useValue: SignalR
    }]
})
export class SignalRModule {

    public static configure(configuration: SignalRConfiguration): ModuleWithProviders {
        return {
            ngModule: SignalRModule,
            providers: [
                { provide: SIGNALR_CONFIGURATION, useValue: configuration },
                {
                    provide: SignalR,
                    useFactory: signalrFactory,
                    deps: [NgZone, SIGNALR_CONFIGURATION]
                },
            ],
        };
    }
}
```

**Comment by HNeukermans** [comment]
Hey @pdunlop,
 
AOT support? Cool stuff. 
If you like to create a pull request, I would be happy to merge it in?

I think this is a very valueable contribution.
Glad, you like the library.

**Comment by HNeukermans** [comment]
I found this on this ngx-translate readme: 
AoT

If you want to configure a custom TranslateLoader while using AoT compilation or Ionic 2, you must use an exported function instead of an inline function.

export function createTranslateLoader(http: Http) {
    return new TranslateStaticLoader(http, './assets/i18n', '.json');
}

@NgModule({
    imports: [
        BrowserModule,
        HttpModule,
        TranslateModule.forRoot({
            provide: TranslateLoader,
            useFactory: (createTranslateLoader),
            deps: [Http]
        })
    ],
    bootstrap: [AppComponent]
})
export class AppModule { }

**Comment by HNeukermans** [comment]
changed module, so it now uses a exported factory function
